<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="31665" started-at="2018-11-19T04:22:46Z" finished-at="2018-11-19T04:23:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="31665" started-at="2018-11-19T04:22:46Z" finished-at="2018-11-19T04:23:18Z">
      <class name="Railway.LoginTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@40e60ece]" name="beforeMethod" is-config="true" duration-ms="6439" started-at="2018-11-19T04:22:46Z" finished-at="2018-11-19T04:22:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC01()[pri:0, instance:Railway.LoginTest@40e60ece]" name="TC01" duration-ms="1713" started-at="2018-11-19T04:22:53Z" finished-at="2018-11-19T04:22:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:Railway.LoginTest@40e60ece]" name="afterMethod" is-config="true" duration-ms="699" started-at="2018-11-19T04:22:55Z" finished-at="2018-11-19T04:22:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@40e60ece]" name="beforeMethod" is-config="true" duration-ms="3502" started-at="2018-11-19T04:22:55Z" finished-at="2018-11-19T04:22:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC02()[pri:0, instance:Railway.LoginTest@40e60ece]" name="TC02" duration-ms="1139" started-at="2018-11-19T04:22:59Z" finished-at="2018-11-19T04:23:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:Railway.LoginTest@40e60ece]" name="afterMethod" is-config="true" duration-ms="674" started-at="2018-11-19T04:23:00Z" finished-at="2018-11-19T04:23:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@40e60ece]" name="beforeMethod" is-config="true" duration-ms="3487" started-at="2018-11-19T04:23:01Z" finished-at="2018-11-19T04:23:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TC03()[pri:0, instance:Railway.LoginTest@40e60ece]" name="TC03" duration-ms="1480" started-at="2018-11-19T04:23:04Z" finished-at="2018-11-19T04:23:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error message is display as expected expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error message is display as expected expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Railway.LoginTest.TC03(LoginTest.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:Railway.LoginTest@40e60ece]" name="afterMethod" is-config="true" duration-ms="686" started-at="2018-11-19T04:23:06Z" finished-at="2018-11-19T04:23:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@40e60ece]" name="beforeMethod" is-config="true" duration-ms="3484" started-at="2018-11-19T04:23:06Z" finished-at="2018-11-19T04:23:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC04()[pri:0, instance:Railway.LoginTest@40e60ece]" name="TC04" duration-ms="919" started-at="2018-11-19T04:23:10Z" finished-at="2018-11-19T04:23:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:Railway.LoginTest@40e60ece]" name="afterMethod" is-config="true" duration-ms="648" started-at="2018-11-19T04:23:11Z" finished-at="2018-11-19T04:23:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@40e60ece]" name="beforeMethod" is-config="true" duration-ms="3604" started-at="2018-11-19T04:23:11Z" finished-at="2018-11-19T04:23:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TC05()[pri:0, instance:Railway.LoginTest@40e60ece]" name="TC05" duration-ms="2422" started-at="2018-11-19T04:23:15Z" finished-at="2018-11-19T04:23:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error message is display as expected expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error message is display as expected expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Railway.LoginTest.TC05(LoginTest.java:97)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC05 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:Railway.LoginTest@40e60ece]" name="afterMethod" is-config="true" duration-ms="658" started-at="2018-11-19T04:23:17Z" finished-at="2018-11-19T04:23:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- Railway.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
